const shortTexts = [
  'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump.',
  'She sells sea shells by the sea shore. The shells she sells are surely seashells. So if she sells shells on the seashore, I am sure she sells seashore shells.',
  'Peter Piper picked a peck of pickled peppers. A peck of pickled peppers Peter Piper picked. If Peter Piper picked a peck of pickled peppers, where is the peck of pickled peppers.',
  'A proper cup of coffee from a proper copper coffee pot. I am not a pheasant plucker, I am a pheasant pluckers son. I am only plucking pheasants till the pheasant pluckers come.',
  'Six slick hicks with sticks and bricks are in the mix. Thin sticks, thick bricks, sick tricks. Quick fix, slick tricks, six slick hicks.',
  'Betty bought a bit of butter. But the butter Betty bought was bitter. So Betty bought a better butter, and it made her batter better.',
  'How much wood would a woodchuck chuck if a woodchuck could chuck wood. He would chuck as much wood as a woodchuck could if a woodchuck could chuck wood.',
  'Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasnt very fuzzy, was he.',
  'Through three cheese trees three free fleas flew. While these fleas flew, freezy breeze blew. Freezy breeze made these three trees freeze.',
  'I saw Susie sitting in a shoe shine shop. Where she sits she shines, and where she shines she sits.',
]

const mediumTexts = [
  'The sunset painted the sky in shades of orange and pink as the waves crashed against the shore. Seagulls called out overhead while a gentle breeze carried the salty scent of the ocean. Children laughed and played in the sand, building castles that would soon be washed away by the rising tide. In the distance, a sailboat drifted lazily on the horizon, its white canvas catching the last rays of sunlight. It was the kind of evening that made you forget about time, a perfect moment suspended between day and night.',
  'Technology has transformed the way we communicate, work, and live. What once required hours of effort can now be accomplished in seconds with the tap of a finger. Information flows freely across borders and time zones, connecting people who might never meet in person. Yet amid this digital revolution, there remains something irreplaceable about face-to-face conversation, the warmth of a genuine smile, the comfort of a shared silence. The challenge of our age is not to choose between the virtual and the real, but to find harmony between them.',
  'The library was quiet except for the occasional rustle of pages and the soft hum of fluorescent lights. Rows upon rows of books lined the walls, their spines forming a colorful mosaic of knowledge and imagination. An old man sat in the corner, lost in a worn-out novel from decades past. Nearby, a student furiously scribbled notes for an exam, surrounded by stacks of reference materials. In the children section, a mother read aloud to her daughter, bringing words on a page to life with animated voices and gestures. This was a sanctuary of stories.',
  'Mountain hiking is an experience that tests both body and mind. The trail begins gently enough, winding through cool forests where sunlight filters through the canopy. Birds chirp from hidden branches and small streams cross the path, their water clear and cold. As the elevation increases, the trees grow shorter and thinner, giving way to rocky terrain. Each step becomes deliberate, muscles straining against the incline. But reaching the summit makes it all worthwhile. The view stretches for miles, a patchwork of valleys, lakes, and distant peaks. The wind carries the silence of heights.',
  'Cooking is an art that engages all the senses. The sizzle of onions hitting a hot pan, the aroma of garlic and herbs filling the kitchen, the vibrant colors of fresh produce arranged on a cutting board. Each ingredient tells a story of soil and sun, of farmers markets and foreign lands. A dash of salt awakens flavors, a squeeze of lemon brightens a dish. The process requires patience and intuition, knowing when to stir and when to let things rest. And in the end, there is the joy of sharing what you have created with others.',
]

const longTexts = [
  'The old house stood at the end of a winding gravel road, surrounded by ancient oaks whose branches reached toward the sky like gnarled fingers. It had been abandoned for decades, its windows boarded up and its paint peeling away in long strips that fluttered in the wind. Local children dared each other to approach its front door, telling stories of ghosts and hidden treasure that had grown more elaborate with each passing generation. But the truth about the house was far more interesting than any legend. It had once belonged to a reclusive inventor who filled its rooms with strange contraptions and half-finished machines. Some said he had been trying to build a flying machine long before the Wright brothers took to the skies. Others claimed he had discovered a way to harness electricity from lightning itself. The truth, as with most things, lay somewhere in between. The inventor had been a dreamer, a man ahead of his time who never quite managed to turn his visions into reality. His notebooks, found years later in the attic, contained detailed sketches of devices that would not be invented for another fifty years. Flying cars, portable telephones, machines that could think. He had imagined it all.',
  'Artificial intelligence is no longer a concept confined to science fiction novels and futuristic movies. It has become an integral part of our daily lives, from the voice assistants that respond to our commands to the algorithms that recommend what we should watch, read, or buy. Machine learning models analyze vast amounts of data to identify patterns that human minds might never notice, making everything from medical diagnoses to financial predictions more accurate than ever before. Yet with these advances come profound questions about privacy, employment, and the very nature of consciousness. Will machines eventually surpass human intelligence? What happens to jobs when automation can perform tasks more efficiently than people? How do we ensure that AI systems make ethical decisions? These are not questions for technologists alone. They require input from philosophers, policymakers, and the public at large. The future of AI is not predetermined. It will be shaped by the choices we make today, the regulations we put in place, and the values we choose to embed into our systems. The responsibility lies with all of us.',
  'The ocean covers more than seventy percent of our planets surface, yet we have explored less than twenty percent of it. Beneath the waves lies a world of extraordinary beauty and mystery, from coral reefs teeming with colorful fish to deep-sea trenches where strange creatures dwell in eternal darkness. The health of our oceans is inextricably linked to the health of our planet. They regulate our climate, produce more than half of the oxygen we breathe, and provide food and livelihoods for billions of people. But human activities are taking a heavy toll. Overfishing has depleted many fish stocks, plastic pollution has reached every corner of the marine environment, and rising ocean temperatures are causing coral bleaching on a massive scale. The good news is that we have the knowledge and tools to address these challenges. Marine protected areas have proven effective at allowing ecosystems to recover. Sustainable fishing practices can ensure that we continue to benefit from the oceans resources without depleting them. Reductions in carbon emissions can slow the warming and acidification of seawater. What is needed now is the collective will to act, to recognize that the fate of the oceans is our fate too.',
]

export function getRandomText(length: 'short' | 'medium' | 'long'): string {
  const pool = length === 'short' ? shortTexts : length === 'medium' ? mediumTexts : longTexts
  return pool[Math.floor(Math.random() * pool.length)]
}
